### ISSUE TITLE
QRCode oversize

### ISSUE THREAD

**Issue by tentenlee100** [EyreFree/EFQRCode#11]
使用1.2.4版本 使用example裡面的程式直接建立qrcode整個qrcode就跑掉了，只會顯示一個區塊而已
再麻煩看一下，

ios版本是9.3 iphone 6

![screen shot 2017-05-10 at 21 58 59](https://cloud.githubusercontent.com/assets/11982625/25902413/110f2106-35cc-11e7-9ec5-c068c9a66832.png)

**Comment by EyreFree** [comment]
你好：
1. 可以提供一下具体生成参数么？
2. 然后保存到相册能否查看到完整二维码图片？

**Comment by tentenlee100** [comment]
@EyreFree 
直接整包zip下載解開後，直接run參數都不改，就變這樣，存下來也一樣是長這樣

**Comment by EyreFree** [comment]
我这里目前无法复现该问题，能否麻烦将 watermark 参数设为 WWF 然后将生成页面截图给我看一下？

**Comment by tentenlee100** [comment]
@EyreFree 
換了一支手機後就正常
會出問題的目前只遇到iphone6 上 9.3.5
請問wwf是什麼東西呀？

是這樣嗎？
![screen shot 2017-05-11 at 15 17 30](https://cloud.githubusercontent.com/assets/11982625/25937099/01dac820-365d-11e7-9e13-2213bb5c7f4e.png)

**Comment by EyreFree** [comment]
唔，这个也行...

虽然还是看不出啥问题，😂

我去下个 9.3.5 模拟器看看...

**Comment by tentenlee100** [comment]
@EyreFree 
模擬器正常，我測試過了，所以我才說實機才有這問題，不確定是否是只有我這隻手機才有問題而已....

**Comment by EyreFree** [comment]
那这就很尴尬了...

目前没发现有设备能复现的...

😂

**Comment by tentenlee100** [comment]
@EyreFree 
最後我用以前我自己以前寫的程式跑就正常，給你參考看看

```
func getQrcodeImage(qrcodeString:String) -> UIImage?{
        guard  let qrFilter = CIFilter(name:"CIQRCodeGenerator") else {
            return nil
        }
        qrFilter.setDefaults()
        
        guard let infoData = qrcodeString.data(using: String.Encoding.utf8) else {
            return nil
        }
        qrFilter.setValue(infoData, forKey: "inputMessage")
        
        guard let ciImage = qrFilter.outputImage else {
            return nil
        }
        
        let cgImage = CIContext(options:nil).createCGImage(ciImage, from: ciImage.extent)
        
        let qrcodeImage = UIImage(cgImage:cgImage!)
        
        let imageWidth : CGFloat = 240.0
        
        UIGraphicsBeginImageContext(CGSize(width: imageWidth, height: imageWidth))
        
        let  resizeContext = UIGraphicsGetCurrentContext();
        resizeContext!.interpolationQuality = CGInterpolationQuality.none;
        
        qrcodeImage.draw(in: CGRect(x: 0.0 , y: 0.0 ,width: imageWidth , height:  imageWidth))
        let resizedImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext();
        
        return resizedImage
        
        
    }
```

**Comment by EyreFree** [comment]
好的，感谢，🙏

**Comment by ChengGC** [comment]
我ios10的手机没事，iOS9的ipad和他一样有这个问题

**Comment by Zrocky** [comment]
iOS 9.3.4   iPod真机  发生同样错误，测试过模拟器iOS9完全正常
![img_0247](https://cloud.githubusercontent.com/assets/8621246/26340090/03bcb1ba-3fbf-11e7-9b3c-838aa0447418.PNG)

**Comment by EyreFree** [comment]
@tentenlee100 @ChengGC @Zrocky 

Fixed in [1.2.5](https://github.com/EyreFree/EFQRCode/releases/tag/1.2.5).
