### ISSUE TITLE
发现在iOS10以下的版本有兼容性问题

### ISSUE THREAD

**Issue by wsxiaoluob** [EyreFree/EFQRCode#16]
在iOS9.3的设备上，用这个库生成的二维码图片在微信中都无法识别
![Alt text](http://img.shenghuozhe.net/shz/2017/06/05/204w_208h_252A41496637398.png)
很明显图片有问题
请问有人遇到过这种问题嘛？在iOS8上也有类似问题，我的调用代码如下：

![Alt text](http://img.shenghuozhe.net/shz/2017/06/05/1574w_140h_5F1E61496637585.png)

**Comment by EyreFree** [comment]
已确认此问题为 Bug，

[1.2.5](https://github.com/EyreFree/EFQRCode/releases/tag/1.2.5) 版本已修复，

可尝试替换为最新版以解决该问题。

**Comment by wsxiaoluob** [comment]
已解决，多谢
