### ISSUE TITLE
generate can't be read by some qrcode reader(quickMark)

### ISSUE THREAD

**Issue by tentenlee100** [EyreFree/EFQRCode#17]
as title 

code:
```
        if   let tryCGImage = EFQRCode.generate(
            content: "FCYKrciaHgodSKn3baKuPzas0k2PQJjI",
            size: EFIntSize(width: 240, height: 240)
            ) {
            let image = UIImage(cgImage: tryCGImage)
            qrcodeImageView?.image = image
            qrcodeImageView?.contentMode = .center
        }
```
![screen shot 2017-06-08 at 14 10 56](https://user-images.githubusercontent.com/11982625/26914575-b4150e8a-4c54-11e7-9a1d-17f990d44f64.png)

**Comment by EyreFree** [comment]
Dot matrix two-dimensional code generated by the official apple API, EFQRCode did not modify the two-dimensional code matrix content, and tested using 10 different two-dimensional code scanner, only quickMark can not recognize, so I personally think that quickMark may be not support certain encoding.

**Comment by EyreFree** [comment]
Next I may change to generate matrix in some other way, maybe quickMark can read, and I also wish quickMark can find this problem too, because this is not my problem, actually, 🤔

**Comment by tentenlee100** [comment]
this is another function to mark the qrcode.
it do not have gray line in edge
is it issue on create image ?

![screen shot 2017-06-09 at 19 46 04](https://user-images.githubusercontent.com/11982625/26974089-5a0322da-4d4c-11e7-9a57-10c263a1fcb9.png)

**Comment by EyreFree** [comment]
No, it's not, EFQRCode will not add gray line in the edge of the picture and there were no similar reports before.

I think you should check the `contentMode ` of the `UIImageView ` you use, maybe it is caused by this.
