### ISSUE TITLE
Generated QR Code not match with CIImage generated

### ISSUE THREAD

**Issue by Haraguroicha** [EyreFree/EFQRCode#21]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EyreFree/EFQRCode/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EyreFree/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

Inspect from func `CIImage.generateQRCode()`, the `qrFilter.outputImage` output correctly with following image

![image](https://user-images.githubusercontent.com/1715541/28531666-21daa8d6-705d-11e7-91e9-def02a0e2413.png)

But func `EFQRCodeGenerator.generate()` result in following wrong image

![image](https://user-images.githubusercontent.com/1715541/28531523-b039e3ae-705c-11e7-846b-3b4740ee8c0e.png)

#### Reproduce

none

#### Other Comment

change `codes[indexY][indexX]` to `codes[indexX][indexY] ` 3 times in `EFQRCodeGenerator.swift` will resolve this issue

**Comment by FrankWu100** [comment]
MERGE!!! PLS!!!

**Comment by EyreFree** [comment]
Fixed in [1.2.6](https://github.com/EyreFree/EFQRCode/releases/tag/1.2.6), @Haraguroicha @FrankWu100 .
