### ISSUE TITLE
请问有没有oc版本的

### ISSUE THREAD

**Issue by ld18684737932** [EyreFree/EFQRCode#26]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/EyreFree/EFQRCode/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/EyreFree/EFQRCode/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
参考 [issues #23](https://github.com/EyreFree/EFQRCode/issues/23)。
