### ISSUE TITLE
Using EFQRCode images with normal QR code readers

### ISSUE THREAD

**Issue by zackshapiro** [EyreFree/EFQRCode#33]
Hey there, 

Thanks for making this! Before I use it in my project,  I was wondering since you can embed multiple codes in an image, how a standard QR code reader will read this, if at all. 

I'm just putting one string in my QR code but I want other devices to be able to use they reader to read my codes. Will that work automatically for my use-case?

**Comment by EyreFree** [comment]
Well, I don't know how you understand it, but there's not "multiple codes" in a QR code image. In fact, this project only adds some styles to the ordinary QR code image, that is to say, besides looking beautiful, other aspects are similar to ordinary QR code image.

I tested with about 20+ QR code readers software on AppStore, and all of them can be recognized normally (if your style is not very exaggerated). That is to say, you can use the generation and recognition of this project separately, use them together is not necessary.

However, as an insurance, it is suggested that you choose your own style parameters and then test the generated two-dimensional code with the scavenging software you want to identify.
