### ISSUE TITLE
EFUIntPixel init?(color: CGColor)  always return nil

### ISSUE THREAD

**Issue by vin-zhou** [EyreFree/EFQRCode#37]
Hi, 
In EFUIntPixelr.swift Line 66, it will always return nil when init by CGColor. Thus, function  CGImage.binarization() will not be called. It's weird to see this useless  function and initializer.

**Comment by vin-zhou** [comment]
QRCode is a square.

**Comment by JackLChen** [comment]
I also found this. So fork the repository and fix it with return keyword for `EFDefine.swift`   @EyreFree 

```

public struct EFUIntPixel {
    public var red: UInt8 = 0
    public var green: UInt8 = 0
    public var blue: UInt8 = 0
    public var alpha: UInt8 = 0

    init(red: UInt8, green: UInt8, blue: UInt8, alpha: UInt8) {
        self.red = red
        self.green = green
        self.blue = blue
        self.alpha = alpha
    }

    init?(color: CGColor) {
        if let components = color.components, 4 == color.numberOfComponents {
            self.init(
                red: UInt8(components[0] * 255.0),
                green: UInt8(components[1] * 255.0),
                blue: UInt8(components[2] * 255.0),
                alpha: UInt8(components[3] * 255.0)
            )
            return
        }
        return nil
    }
}

```

**Comment by vin-zhou** [comment]
@EyreFree    do "binarization" is to set the image just in black/white 2 colors,  the CGImage.binarization() doesn't work since it use foreground/background color, is it right?

@JackLChen I also found in some color (such as blue) in kCGColorSpaceDeviceGray only contains 2 components, so the init may also wrongly return nil.

**Comment by JackLChen** [comment]
yeah. Hope that `EyreFree` will fix it soon.

**Comment by ApolloZhu** [comment]
@vin-zhou @LegendChan please check to see if the master branch have fixed the problem.

**Comment by ApolloZhu** [comment]
We assume the bug is fixed. If it's still not working for you, leave a comment or discuss in the QQ group.
