### ISSUE TITLE
Error when running pod install for 4.2.1

### ISSUE THREAD

**Issue by junweimah** [EyreFree/EFQRCode#39]
I am running xcode 9.2 using swift 4, I have this line in my pod file: 

  `pod 'EFQRCode', '~> 4.2.1'`

When running pod install, i get this : 

![image](https://user-images.githubusercontent.com/21700014/36086790-3c5605ba-1009-11e8-9e58-af3086e35f0d.png)

But when i try to put just `   pod 'EFQRCode'   `, without the version, I can successfully run pod install without error, but the version is 4.0.0

Any ideas?

Thanks

**Comment by EyreFree** [comment]
`pod repo update`

**Comment by junweimah** [comment]
Thanks
