### ISSUE TITLE
can't get image

### ISSUE THREAD

**Issue by 595650661** [EyreFree/EFQRCode#40]
if let tryImage = EFQRCode.generate(content: "美少女战士",
                                            size: EFIntSize.init(width: 120, height: 120),
                                            backgroundColor: UIColor.orange.cgColor,
                                            foregroundColor: UIColor.yellow.cgColor,
                                            watermark: UIImage.init(named: "dog.png")?.toCGImage()) {
            
            imageView.image? = UIImage.init(cgImage: tryImage)
        }

above,It doesn't work.When I invoke like this, 
        if let tmpImage = EFQRCode.generate(content: "美少女战士",
                                            watermark: UIImage.init(named: "dog.png")?.toCGImage()) {
            
            imageView.image = UIImage.init(cgImage: tmpImage)
        }
it works.why ?

**Comment by ApolloZhu** [comment]
Try to remove the extra `?` after `imageView.image`

<details>
<summary>Why?</summary>

![image](https://user-images.githubusercontent.com/10842684/39032352-1c5511f0-443b-11e8-91c4-d1c631402653.png)
</details>

**Comment by ApolloZhu** [comment]
Please reopen if you believe this is indeed a bug of EFQRCode.
