### ISSUE TITLE
有没有直接是水印覆盖在二维码中心一小块的那种样式 类似微信那种

### ISSUE THREAD

**Issue by phpmaple** [EyreFree/EFQRCode#44]

**Comment by EllisShen** [comment]
希望有這樣的功能

**Comment by nzmax** [comment]
你直接把水印加到UIImage上面不就行喽

**Comment by ApolloZhu** [comment]
[`EFQRCodeGenerator.setIcon(icon:size:)`](https://github.com/EyreFree/EFQRCode/blob/c4e5459371cd2d72425c6c922b01afe986879df5/Source/EFQRCodeGenerator.swift#L131)
