### ISSUE TITLE
Cross Platform Functionality

### ISSUE THREAD

**Issue by cdeck95** [EyreFree/EFQRCode#49]
Probably a stupid question, but Is this library necessary to decode the QR code? Or can a normal QR code scanner read the data?

I would imagine a normal QR code scanner could read the data, but want to be sure before I implement it. 

End goal: read the QR code in my Android App

**Comment by ApolloZhu** [comment]
TL;DR: check out https://github.com/zxing/zxing, or google your end goal to find other options

To answer your questions: No. Yes.

As specified in the README file, this only supports Apple platforms. That's because the implementation relies on Apple's `CoreImage` framework to do the actual job.
